project:
  type: website
  render: 
    - "*qmd"
    - "!misc"
  output-dir: "docs"

website:
  title: "ChiSocNet Summer School -- 2026"
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - href: program.qmd
        text: Program
      - href: keynotes.qmd
        text: Keynotes
    right:
      - text: "2024"
        menu:
          - href: 2024/index.qmd
            text: Home
          - href: 2024/program.qmd
            text: Program
          - href: 2024/keynotes.qmd
            text: Keynotes
      - href: about.qmd
        text: ChiSocNet
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



