---
title: Program
---

::: {.callout-note}
This program is subject to change.
:::

## Course requirements

No prior knowledge of social network analysis is assumed for this
course. However, it would be useful to read *Doing social network
research* (Robins, 2015). SAGE Publications Ltd.* *

## Who is this course for?

Postgraduate research students, postdocs and academics wishing to use
Social Networks in their research.

## Recommended reading

Borgatti, S. P., Everett, M. G., Johnson, J. C. & Agneessens, F. (2022).
*Analyzing social networks using R*. Sage.

Rawling, C., Smith, J.A., Moody, J. & McFarland, D. (2023). *Network Analysis: Integrating Social Network Theory, Method, and Application with R*. Cambridge University Press.

Scott, J. (2017). *Social Network Analysis: A Handbook*. Sage.

## Language

Summer school courses will be taught in English unless all the
participants are proficient in Spanish.

## Course leaders:

Dr Alejandro Espinosa-Rada (Institute of Sociology, Pontifical Catholic University of Chile)

Dr Diego Palacios (Society and Health Research Center, Universidad
Mayor)

Dr Francisca Ortiz Ruiz (Center for Economics and Social Policies, Universidad
Mayor)

Dr George Vega Yon (Division of Epidemiology, The University of Utah)

## Program

```{r}
#| label: program
#| echo: false
x <- data.table::fread("program.csv")

x[] <- lapply(x, function(col) {
  if (is.character(col)) iconv(col, from = "", to = "UTF-8") else col
})

knitr::kable(x)

```

*\*Summer school registration will be at 8.30*